/**
 * Simplified Groth16-like Verifier
 *
 * Verifies a proof using the BN254 pairing. The verification equation is:
 *
 *   e(piA, piB) == e(alpha*G1, beta*G2) * e(IC, gamma*G2) * e(piC, delta*G2)
 *
 * Where IC is the aggregated public input commitment:
 *   IC = ic[0] + sum_{i=1..l} publicInput[i] * ic[i]
 *
 * We check this by verifying:
 *   e(piA, piB) * e(-alpha*G1, beta*G2) * e(-IC, gamma*G2) * e(-piC, delta*G2) == 1
 *
 * Which is equivalent to a single multi-pairing check.
 */

import { bn254 } from "@noble/curves/bn254";
import type { VerificationKey, Proof } from "./prover.js";
import { FIELD_ORDER } from "./prover.js";

const G1 = bn254.G1;
const Fr = bn254.fields.Fr;

type G1Point = ReturnType<typeof G1.ProjectivePoint.fromHex>;

/**
 * Verify a Groth16-like proof.
 *
 * @param vk         The verification key from trusted setup
 * @param proof      The proof generated by the prover
 * @param publicInputs  The public inputs (wire values for public wires, NOT including wire 0)
 * @returns true if the proof is valid
 */
export function verify(
  vk: VerificationKey,
  proof: Proof,
  publicInputs: bigint[]
): boolean {
  try {
    // Compute the public input commitment: IC = ic[0] + sum(input_i * ic[i+1])
    let icPoint: G1Point = vk.ic[0];
    for (let i = 0; i < publicInputs.length; i++) {
      const term = vk.ic[i + 1].multiply(publicInputs[i]);
      icPoint = icPoint.add(term);
    }

    // Verification via pairings:
    // e(piA, piB) = e(alphaG1, betaG2) * e(IC, gammaG2) * e(piC, deltaG2)
    //
    // Rearranged as multi-pairing check:
    // e(piA, piB) * e(-alphaG1, betaG2) * e(-IC, gammaG2) * e(-piC, deltaG2) == 1

    const negAlphaG1 = vk.alphaG1.negate();
    const negIC = icPoint.negate();
    const negPiC = proof.piC.negate();

    // Use bn254 pairings
    const pairingResult = bn254.pairingBatch([
      { g1: proof.piA, g2: proof.piB },
      { g1: negAlphaG1, g2: vk.betaG2 },
      { g1: negIC, g2: vk.gammaG2 },
      { g1: negPiC, g2: vk.deltaG2 },
    ]);

    // The result of a valid proof pairing should be the identity element (Fp12.ONE)
    return bn254.fields.Fp12.eql(pairingResult, bn254.fields.Fp12.ONE);
  } catch (error) {
    console.error("Verification failed with error:", error);
    return false;
  }
}

/** Serialized representation of a G1 affine point */
interface SerializedG1 {
  x: string;
  y: string;
}

/** Serialized representation of a G2 affine point (Fp2 coordinates) */
interface SerializedG2 {
  x: { c0: string; c1: string };
  y: { c0: string; c1: string };
}

export interface SerializedProof {
  piA: SerializedG1;
  piB: SerializedG2;
  piC: SerializedG1;
}

function serializeG1(point: G1Point): SerializedG1 {
  const aff = point.toAffine();
  return { x: aff.x.toString(), y: aff.y.toString() };
}

function serializeG2(
  point: ReturnType<typeof bn254.G2.ProjectivePoint.fromHex>
): SerializedG2 {
  const aff = point.toAffine();
  const x = aff.x as unknown as { c0: bigint; c1: bigint };
  const y = aff.y as unknown as { c0: bigint; c1: bigint };
  return {
    x: { c0: x.c0.toString(), c1: x.c1.toString() },
    y: { c0: y.c0.toString(), c1: y.c1.toString() },
  };
}

function deserializeG1(data: SerializedG1): G1Point {
  return G1.ProjectivePoint.fromAffine({
    x: BigInt(data.x),
    y: BigInt(data.y),
  });
}

function deserializeG2(
  data: SerializedG2
): ReturnType<typeof bn254.G2.ProjectivePoint.fromHex> {
  const Fp2 = bn254.fields.Fp2;
  return bn254.G2.ProjectivePoint.fromAffine({
    x: Fp2.fromBigTuple([BigInt(data.x.c0), BigInt(data.x.c1)]),
    y: Fp2.fromBigTuple([BigInt(data.y.c0), BigInt(data.y.c1)]),
  });
}

/**
 * Serialize a proof to a JSON-compatible object for transmission.
 */
export function serializeProof(proof: Proof): SerializedProof {
  return {
    piA: serializeG1(proof.piA),
    piB: serializeG2(proof.piB),
    piC: serializeG1(proof.piC),
  };
}

/**
 * Deserialize a proof from its JSON representation.
 */
export function deserializeProof(data: SerializedProof): Proof {
  return {
    piA: deserializeG1(data.piA),
    piB: deserializeG2(data.piB),
    piC: deserializeG1(data.piC),
  };
}
