/**
 * Simplified Groth16-like Verifier
 *
 * Verifies a proof using the BN254 pairing. The verification equation is:
 *
 *   e(piA, piB) == e(alpha*G1, beta*G2) * e(IC, gamma*G2) * e(piC, delta*G2)
 *
 * Where IC is the aggregated public input commitment:
 *   IC = ic[0] + sum_{i=1..l} publicInput[i] * ic[i]
 *
 * We check this by verifying:
 *   e(piA, piB) * e(-alpha*G1, beta*G2) * e(-IC, gamma*G2) * e(-piC, delta*G2) == 1
 *
 * Which is equivalent to a single multi-pairing check.
 */

import { bn254 } from "@noble/curves/bn254";
import type { VerificationKey, Proof } from "./prover.js";
import { FIELD_ORDER } from "./prover.js";

const G1 = bn254.G1;
const Fr = bn254.fields.Fr;

type G1Point = ReturnType<typeof G1.ProjectivePoint.fromHex>;

/**
 * Verify a Groth16-like proof.
 *
 * @param vk         The verification key from trusted setup
 * @param proof      The proof generated by the prover
 * @param publicInputs  The public inputs (wire values for public wires, NOT including wire 0)
 * @returns true if the proof is valid
 */
export function verify(
  vk: VerificationKey,
  proof: Proof,
  publicInputs: bigint[]
): boolean {
  try {
    // Compute the public input commitment: IC = ic[0] + sum(input_i * ic[i+1])
    let icPoint: G1Point = vk.ic[0];
    for (let i = 0; i < publicInputs.length; i++) {
      const term = vk.ic[i + 1].multiply(publicInputs[i]);
      icPoint = icPoint.add(term);
    }

    // Verification via pairings:
    // e(piA, piB) = e(alphaG1, betaG2) * e(IC, gammaG2) * e(piC, deltaG2)
    //
    // Rearranged as multi-pairing check:
    // e(piA, piB) * e(-alphaG1, betaG2) * e(-IC, gammaG2) * e(-piC, deltaG2) == 1

    const negAlphaG1 = vk.alphaG1.negate();
    const negIC = icPoint.negate();
    const negPiC = proof.piC.negate();

    // Use bn254 pairings
    const pairingResult = bn254.pairingBatch([
      { g1: proof.piA, g2: proof.piB },
      { g1: negAlphaG1, g2: vk.betaG2 },
      { g1: negIC, g2: vk.gammaG2 },
      { g1: negPiC, g2: vk.deltaG2 },
    ]);

    // The result of a valid proof pairing should be the identity element (Fp12.ONE)
    return bn254.fields.Fp12.eql(pairingResult, bn254.fields.Fp12.ONE);
  } catch (error) {
    console.error("Verification failed with error:", error);
    return false;
  }
}

/**
 * Serialize a proof to a JSON-compatible object for transmission.
 */
export function serializeProof(proof: Proof): {
  piA: string;
  piB: string;
  piC: string;
} {
  return {
    piA: bytesToHex(proof.piA.toRawBytes()),
    piB: bytesToHex(proof.piB.toRawBytes()),
    piC: bytesToHex(proof.piC.toRawBytes()),
  };
}

/**
 * Deserialize a proof from its JSON representation.
 */
export function deserializeProof(data: {
  piA: string;
  piB: string;
  piC: string;
}): Proof {
  return {
    piA: G1.ProjectivePoint.fromHex(hexToBytes(data.piA)),
    piB: bn254.G2.ProjectivePoint.fromHex(hexToBytes(data.piB)),
    piC: G1.ProjectivePoint.fromHex(hexToBytes(data.piC)),
  };
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}
